(define (domain sokoban-domain)
  (:requirements :equality)
  (:predicates (has_player ?x)
               (has_box ?x)
               (adjacent ?x ?y ?dir))
  (:action move-player
           :parameters (?dir ?x ?y)
           :precondition (and (adjacent ?x ?y ?dir)
                              (not (has_box ?y))
                              (has_player ?x))
           :effect		   (and (has_player ?y)
                              (not (has_player ?x))))
  (:action push-box
		   :parameters (?dir ?x ?y ?z)
		   :precondition (and (has_player ?x)
                          (has_box ?y)
                          (not (has_box ?z))
                          (adjacent ?x ?y ?dir)
                          (adjacent ?y ?z ?dir))
	       :effect (and (has_box ?z)
						(not(has_box ?y))
						(has_player ?y)
						(not(has_player ?x))))
  )

